# TENSOR WITH PYTORCH

In [1]:
import torch
import numpy as np
import pandas as pd

In [2]:
z = torch.zeros(5,3)
print(z)
print(z.dtype)   

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
torch.float32


## Above, we created a 5x3 Matrix filled with zeros, and query its datatypes to fidout that that the zeros are 32-bit floating point numbers, which is the default in Pytorch


## If we wanted integers instead, then we can override the dafault. Like so Below..

In [4]:
i = torch.ones((5, 3), dtype=torch.int16)
print(i)

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]], dtype=torch.int16)


## Initializing Learning rates randomly with a specific seed

In [7]:
torch.manual_seed(1728)
r = torch.rand(2,2)
print(r)

r1 = torch.rand(2,2)
print('This will be a Different Tensor')
print(r1)

torch.manual_seed(1728)
r2=torch.rand(2,2)
print('\nShould match r')
print(r2)




tensor([[0.4077, 0.1676],
        [0.3299, 0.2215]])
This will be a Different Tensor
tensor([[0.9937, 0.7382],
        [0.3273, 0.5193]])

Should match r
tensor([[0.4077, 0.1676],
        [0.3299, 0.2215]])


### Aritmethic with Pytorch tensors ai Intuitive. Tensors of similar shape may be added or multiplied. Operations btw a scalar and a tensor will distribute over the cells of a tensor.
## EXAMPLES BELOW:

In [16]:
one1s = torch.ones(2, 3)
print(one1s)
tw2s = torch.ones(2,3)*2  #-- Multiply every element in tw3s by 2
print(tw2s)
thr33s = one1s + tw2s  ## Performing Addition Operations'''
print(thr33s)          ## Tensors are added element-wise
print(thr33s.shape)    ## This has the same dimensions as input tensors

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[2., 2., 2.],
        [2., 2., 2.]])
tensor([[3., 3., 3.],
        [3., 3., 3.]])
torch.Size([2, 3])


In [ ]:
r1 = torch.rand(2,3)
r2 = torch.rand(3,2)
r3 = r1+r2 

### ABOVE: Attempting to add two random tensors of different shapes and there is a runtime error because there ios no way to dovelement-wise arithmetic operations with tensors of different shapes 

# TENSORS 1: CREATION AND CONVERSION OF TENSORS

### CREATING A 1-D TENSOR

In [350]:
a = [i+(-7) for i in range(16)]
A = torch.Tensor(a)
print(A.ndimension())
print(type(A))
print(A.type())
print(A.dtype)
A

1
<class 'torch.Tensor'>
torch.FloatTensor
torch.float32


tensor([-7., -6., -5., -4., -3., -2., -1.,  0.,  1.,  2.,  3.,  4.,  5.,  6.,
         7.,  8.])

### INDEXING A TENSOR

In [353]:
print(A[10])
print(A[4],'\n', A[11])


tensor(3.)
tensor(-3.) 
 tensor(4.)


### ACESSING THE ACTUAL NUMBER USING `item()` METHOD

In [359]:
print(A[11].item())
print(type(A[9].item()))
print(A.type())

4.0
<class 'float'>
torch.FloatTensor


### CONVERTING FROM FLOAT TENSOR TO LONG TENSOR USING TYPE()

In [362]:
A.type()

'torch.FloatTensor'

In [389]:
vx = A.type(torch.LongTensor)
vx = vx.type(dtype=torch.int32)

print(vx.type(), vx.dtype, vx)

torch.IntTensor torch.int32 tensor([-7, -6, -5, -4, -3, -2, -1,  0,  1,  2,  3,  4,  5,  6,  7,  8],
       dtype=torch.int32)


### SIZE AND DIMENSION

In [391]:
print(vx)
print(vx.ndimension())
print(vx.size())


tensor([-7, -6, -5, -4, -3, -2, -1,  0,  1,  2,  3,  4,  5,  6,  7,  8],
       dtype=torch.int32)
1
torch.Size([16])


In [392]:
A

tensor([-7., -6., -5., -4., -3., -2., -1.,  0.,  1.,  2.,  3.,  4.,  5.,  6.,
         7.,  8.])

### CHANGING THE VIEW OF A TENSOR

In [399]:
K = A.view(4,4)
Kx = A.view(2,8)
xm = A.view(8,2)
print(K,K.type())
print(Kx, Kx.type())
print(xm, xm.type())

tensor([[-7., -6., -5., -4.],
        [-3., -2., -1.,  0.],
        [ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.]]) torch.FloatTensor
tensor([[-7., -6., -5., -4., -3., -2., -1.,  0.],
        [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.]]) torch.FloatTensor
tensor([[-7., -6.],
        [-5., -4.],
        [-3., -2.],
        [-1.,  0.],
        [ 1.,  2.],
        [ 3.,  4.],
        [ 5.,  6.],
        [ 7.,  8.]]) torch.FloatTensor


In [20]:
n = [6,9,12]
#[2,1,5]

for k in n:
    #print(k)
    a = torch.tensor([i for i in range(k)])
    a_col = a.view(-1,3)
    print('Original tensor:', a)
    print('Reshaped view of tensor with 3cols:\n',a_col)
    print('='*55)

Original tensor: tensor([0, 1, 2, 3, 4, 5])
Reshaped view of tensor with 3cols:
 tensor([[0, 1, 2],
        [3, 4, 5]])
Original tensor: tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])
Reshaped view of tensor with 3cols:
 tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])
Original tensor: tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
Reshaped view of tensor with 3cols:
 tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])


### SWITHCHING BETWEEN TENSOR AND NUMPY 

In [41]:
yx = [[12.4,15],[12,45],[9,7]]
nPy = np.arange(1.0,3.5,0.5)

dx = np.array(yx)
dx

array([[12.4, 15. ],
       [12. , 45. ],
       [ 9. ,  7. ]])

In [44]:
np_2_tensor = torch.from_numpy(dx)
np_2_tensor

tensor([[12.4000, 15.0000],
        [12.0000, 45.0000],
        [ 9.0000,  7.0000]], dtype=torch.float64)

In [45]:
tensor_2_np = np_2_tensor.numpy()
tensor_2_np 

array([[12.4, 15. ],
       [12. , 45. ],
       [ 9. ,  7. ]])

# SIMPLE AMTHEMATICAL OPERATIONS WITH TENSORS

In [46]:
rx = torch.rand(2,2) - 0.5*2
print('A Random Matrix:\n',rx)

print('Absolute Value of rx: \n', torch.abs(rx))
print('Absolute Value of rx: \n', torch.abs(rx))
print('LINEAR ALGEBRAIC OPR like DETERMINANTS AND SINGULAR VALUE DECOMPOSITION:\n',
'Detrminants Of rx:',torch.det(rx), '\n',
'Singular Value Decomposition of rx:', torch.svd(rx), '\n')

print('STATISTICAL AND AGGREGATE OPERATIONS:\n',
    'STANDARD DEVIATION OF rx:', torch.std(rx),'\n',
    'AVERAGE OR MEAN OF rx:', torch.mean(rx),'\n',
    'MAXIMUM VALUE OF rx:', torch.max(rx),'\n'    
)

A Random Matrix:
 tensor([[-0.5143, -0.2787],
        [-0.6243, -0.3068]])
Absolute Value of rx: 
 tensor([[0.5143, 0.2787],
        [0.6243, 0.3068]])
Absolute Value of rx: 
 tensor([[0.5143, 0.2787],
        [0.6243, 0.3068]])
LINEAR ALGEBRAIC OPR like DETERMINANTS AND SINGULAR VALUE DECOMPOSITION:
 Detrminants Of rx: tensor(-0.0162) 
 Singular Value Decomposition of rx: torch.return_types.svd(
U=tensor([[-0.6435, -0.7654],
        [-0.7654,  0.6435]]),
S=tensor([0.9087, 0.0179]),
V=tensor([[ 0.8901, -0.4558],
        [ 0.4558,  0.8901]])) 

STATISTICAL AND AGGREGATE OPERATIONS:
 STANDARD DEVIATION OF rx: tensor(0.1662) 
 AVERAGE OR MEAN OF rx: tensor(-0.4310) 
 MAXIMUM VALUE OF rx: tensor(-0.2787) 



### Vector (Tensor) addition

In [14]:
u = torch.Tensor([1,4,2])
v = torch.Tensor([3,4,5])
w = u+v
x = u*v
print(w,x)

tensor([4., 8., 7.]) tensor([ 3., 16., 10.])


### MULTIPLYING A VECTOR WITH A SCALAR

In [18]:
y = torch.ones(2,3)
print(y)

tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [19]:
z = y*100
print(z)

tensor([[100., 100., 100.],
        [100., 100., 100.]])


### LINEAR COMBINATION

In [20]:
u = torch.Tensor([1,2])
v = torch.Tensor([4,0])
print(u,v)

tensor([1., 2.]) tensor([4., 0.])


In [22]:
w = 3*u 
x = 4*v
print(w,x)
print(w+x)
print(3*u+4*v)

tensor([3., 6.]) tensor([16.,  0.])
tensor([19.,  6.])
tensor([19.,  6.])


### ELEMENT-WISE MULTIPLICATION OF THREE TENSORS

In [26]:
q = torch.Tensor([[20], [10], [10]])
c = torch.Tensor([[0],[0],[5]])
n = torch.Tensor([[11],[11],[0]])
print(q,'\n', c, '\n', n)

tensor([[20.],
        [10.],
        [10.]]) 
 tensor([[0.],
        [0.],
        [5.]]) 
 tensor([[11.],
        [11.],
        [ 0.]])


In [30]:
print(q*c*n)

tensor([[0.],
        [0.],
        [0.]])


### DOT PRODUCT USING `dot` METHOD

In [39]:
a = [1,2,3,4]
b = [2,2,3,9]
A = torch.Tensor(a)
B = torch.Tensor(b)

print(torch.dot(A,B))

tensor(51.)


### MATRIX MULTIPLICATION BETWEEN TENSORS
#### NOTE: The `reshape()` method is used to reshape the tensors to ensure proper matrix multiplication

In [3]:
u = torch.Tensor([1,0,1])
v = torch.Tensor([[20],[10],[25]])
print(u,'\n', v) 

tensor([1., 0., 1.]) 
 tensor([[20.],
        [10.],
        [25.]])


In [19]:
u = u.reshape(1,3)
x = u.reshape(3,1)
print(x)
print(u)
u*x
print(v)
v = v.reshape(1,3)
print(u*v)
print(u.shape,x.shape,v.shape)

tensor([[1.],
        [0.],
        [1.]])
tensor([[1., 0., 1.]])
tensor([[20., 10., 25.]])
tensor([[20.,  0., 25.]])
torch.Size([1, 3]) torch.Size([3, 1]) torch.Size([1, 3])


## TENSOR SCALAR MANIPULATION (ALSO CONSIDERED BRODCASTING)

In [20]:
u = torch.Tensor([1,2,3,4,5,6])
print(u*100)
print(u+0)
print(u+1000)
print(u-20)
print(u/10)

tensor([100., 200., 300., 400., 500., 600.])
tensor([1., 2., 3., 4., 5., 6.])
tensor([1001., 1002., 1003., 1004., 1005., 1006.])
tensor([-19., -18., -17., -16., -15., -14.])
tensor([0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000])


# TENSOR 2: BASICS OF MATRIX OPERATIONS

In [82]:
ls = []

for i in range(3):
    in_list = []
    for j in range(3):
        in_list.append(10*(i+1)+j)
        print(in_list)
    ls.append(in_list)


ls
        

[10]
[10, 11]
[10, 11, 12]
[20]
[20, 21]
[20, 21, 22]
[30]
[30, 31]
[30, 31, 32]


[[10, 11, 12], [20, 21, 22], [30, 31, 32]]

In [88]:
A = torch.Tensor(ls)
B = torch.tensor(ls)
print(A,'\n',B)

tensor([[10., 11., 12.],
        [20., 21., 22.],
        [30., 31., 32.]]) 
 tensor([[10, 11, 12],
        [20, 21, 22],
        [30, 31, 32]])


### DIMENSION, SHAPE AND SIZE OF THE 2-D TENSOR

In [106]:
print('Dimension of the tensor:', A.ndimension())
print('Shape of the TENSOR:', A.shape)
print('Total Size of the TENSOR:', A.size())

Dimension of the tensor: 2
Shape of the TENSOR: torch.Size([3, 3])
Total Size of the TENSOR: torch.Size([3, 3])


### GETTING TOTAL NUMBER OF ELEMENTS

In [110]:
print(np.array(A.size()).prod()) # CASTING SIZE ATTRIBUT TO NDARRAY AND APPLYTING PROD

9


### MATRIX(TENSOR) ADDITION

In [123]:
cx = [[1, 3 ,4], [110,23,223], [22,0,9]]
bx = [[10,1,20],[23,45,60],[11,90,65]]
cx = torch.Tensor(cx)
bx = torch.Tensor(bx)
print(cx)
print(bx)
print(cx.ndimension())
print(bx.ndimension())

tensor([[  1.,   3.,   4.],
        [110.,  23., 223.],
        [ 22.,   0.,   9.]])
tensor([[10.,  1., 20.],
        [23., 45., 60.],
        [11., 90., 65.]])
2
2


In [127]:
bcx = cx+bx
bcx
print(bcx.dtype)

torch.float32


### MULTPLYING MATRIX BY A SCALAR

In [131]:
dx = bcx*0
xs = bcx*-2.8
yx = bcx*-0.7


print(dx)
print(yx)
print(xs, xs.dtype)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([[  -7.7000,   -2.8000,  -16.8000],
        [ -93.1000,  -47.6000, -198.1000],
        [ -23.1000,  -63.0000,  -51.8000]])
tensor([[ -30.8000,  -11.2000,  -67.2000],
        [-372.4000, -190.4000, -792.4000],
        [ -92.4000, -252.0000, -207.2000]]) torch.float32


### ADDING A SCALAR TO A MATRIX

In [135]:
wq = xs+926
wq

tensor([[895.2000, 914.8000, 858.8000],
        [553.6000, 735.6000, 133.6000],
        [833.6000, 674.0000, 718.8000]])

### SLICING AND INDEXING MATRIX (TENSOR)

In [136]:
bx

tensor([[10.,  1., 20.],
        [23., 45., 60.],
        [11., 90., 65.]])

In [137]:
bx[0]

tensor([10.,  1., 20.])

In [139]:
bx[0,2]

tensor(20.)

In [143]:
bx[0,1:3]

tensor([ 1., 20.])

In [163]:
bx[1:3,2]

tensor([60., 65.])

In [164]:
bx

tensor([[10.,  1., 20.],
        [23., 45., 60.],
        [11., 90., 65.]])

In [175]:
bx[[2,2]]

tensor([[11., 90., 65.],
        [11., 90., 65.]])

In [178]:
bx[:2,1:3]

tensor([[ 1., 20.],
        [45., 60.]])

In [258]:
bx[1:,2:3]

tensor([[60.],
        [65.]])

### ELEMENT-WISE PRODCUT OF MATRICES

In [281]:
ax = torch.Tensor([[10,20,30],[30,40,9],[12,12,94],[10,0,30],])
b = torch.Tensor([[10,0,0],[0,89,0],[0,0,1],[0,0,0]])
print(ax,'\n',b)

tensor([[10., 20., 30.],
        [30., 40.,  9.],
        [12., 12., 94.],
        [10.,  0., 30.]]) 
 tensor([[10.,  0.,  0.],
        [ 0., 89.,  0.],
        [ 0.,  0.,  1.],
        [ 0.,  0.,  0.]])


In [296]:
Z = ax*b
c = ax.mm(b)
print(Z)
c

RuntimeError: size mismatch, m1: [4 x 3], m2: [4 x 3] at ..\aten\src\TH/generic/THTensorMath.cpp:961

### FOR MATRIX MULTIPLICATION, THE TENSORS MUST BE ARRANGED PROPERLY IN ORDER TO PREVENT THE ABOVE ERROR

In [300]:
print(ax.size(),b.size())
bn = b.reshape(3,4)
bn

torch.Size([4, 3]) torch.Size([4, 3])


tensor([[10.,  0.,  0.,  0.],
        [89.,  0.,  0.,  0.],
        [ 1.,  0.,  0.,  0.]])

tensor([[10.,  0.,  0.],
        [ 0., 89.,  0.],
        [ 0.,  0.,  1.],
        [ 0.,  0.,  0.]])

In [299]:
wxc = ax.mm(bn)
wxc

tensor([[1910.,    0.,    0.,    0.],
        [3869.,    0.,    0.,    0.],
        [1282.,    0.,    0.,    0.],
        [ 130.,    0.,    0.,    0.]])

### TRANSPOSE OF A 2-D TENSOR (MATRIX)

In [324]:
print(wxc.transpose(-2,0))
print(wxc.transpose(-2,-1))
print(wxc.transpose(-2,-2))
print(wxc.transpose(-1,-1))
print(wxc.transpose(-1,1))
print(wxc.transpose(-1,0))
print(wxc.transpose(1,-1))

tensor([[1910.,    0.,    0.,    0.],
        [3869.,    0.,    0.,    0.],
        [1282.,    0.,    0.,    0.],
        [ 130.,    0.,    0.,    0.]])
tensor([[1910., 3869., 1282.,  130.],
        [   0.,    0.,    0.,    0.],
        [   0.,    0.,    0.,    0.],
        [   0.,    0.,    0.,    0.]])
tensor([[1910.,    0.,    0.,    0.],
        [3869.,    0.,    0.,    0.],
        [1282.,    0.,    0.,    0.],
        [ 130.,    0.,    0.,    0.]])
tensor([[1910.,    0.,    0.,    0.],
        [3869.,    0.,    0.,    0.],
        [1282.,    0.,    0.,    0.],
        [ 130.,    0.,    0.,    0.]])
tensor([[1910.,    0.,    0.,    0.],
        [3869.,    0.,    0.,    0.],
        [1282.,    0.,    0.,    0.],
        [ 130.,    0.,    0.,    0.]])
tensor([[1910., 3869., 1282.,  130.],
        [   0.,    0.,    0.,    0.],
        [   0.,    0.,    0.,    0.],
        [   0.,    0.,    0.,    0.]])
tensor([[1910.,    0.,    0.,    0.],
        [3869.,    0.,    0.,    0.],
      

### THERE ARE BASICALLY THE SAME STUFF THOUGH: ITS JUST SPECIFYING THE DIMENSIONS `dim0`, `dim1` ARGUMENT TO THE METHOD

### MATRIX INVERSE

In [327]:
wxc

tensor([[1910.,    0.,    0.,    0.],
        [3869.,    0.,    0.,    0.],
        [1282.,    0.,    0.,    0.],
        [ 130.,    0.,    0.,    0.]])

In [331]:
torch.Tensor.inverse(wxc)

RuntimeError: Lapack Error getrf : U(2,2) is 0, U is singular at ..\aten\src\TH/generic/THTensorLapack.cpp:468

### DETERMINANT OF A MATRIX


In [333]:
torch.det(wxc)

tensor(0.)